### ISSUE TITLE
需要单独赋值才能显示value吗

### ISSUE THREAD

**Issue by emc2ws** [xiaomitangtang/t-digital-gauge#7]
1、我的option如下：
widgetOption: {
        "gaugeType": "donut",
        "minValue": "0",
        "maxValue": "100",
        "value": 10,
        "showValue": true,
        "valueFont":{
          "family": "Roboto", "style": "normal", "weight": "500", "size": 18, "color": "#ffffff" }
        }

this.gauge = new DigitalGauge(document.getElementById(this.elId), widgetOption);
此时中间的value值不会显示。
必须要单独赋值：
this.gauge.value = Math.random() * 100
//
另外浏览器报js错误如下：
Uncaught ReferenceError: str is not defined
    at e.default.set time [as time] (digitalgauge.js?ba59:1)
    at e.default.set value [as value] (digitalgauge.js?ba59:1)
    at eval (digitalgauge.js?ba59:1)
    at Array.forEach (<anonymous>)

2、在使用控件时，必须要import DigitalGauge from "t-digital-gauge2/dist/digitalgauge";
而不能 import DigitalGauge from "t-digital-gauge2";
否则会报错：
Uncaught TypeError: t_digital_gauge2__WEBPACK_IMPORTED_MODULE_1___default.a is not a constructor

**Comment by xiaomitangtang** [comment]
![image](https://user-images.githubusercontent.com/27951909/91176475-e7a60200-e714-11ea-99cd-df41ef11a2a5.png)
我把你的option  copy过来是可以正常使用的
另外
![image](https://user-images.githubusercontent.com/27951909/91176542-ff7d8600-e714-11ea-8607-7707e32b87fa.png)
这个地方做了转换的，所以，理论上讲，传递字符串类型数字也是可以的



第二个问题
![image](https://user-images.githubusercontent.com/27951909/91176611-1b812780-e715-11ea-8fc4-6982d60459b6.png)
此处导出的是一个对象，内部包含了Knob, Swtich, DigitalGauge  而不只是DigitalGauge  

![image](https://user-images.githubusercontent.com/27951909/91176681-35bb0580-e715-11ea-9901-7ec1b4dea530.png)
build的时候，单独把三个分开编译了一次，所以
import DigitalGauge from "t-digital-gauge2/dist/digitalgauge";  也是可以正常使用，并且不会导入其他两个图表

-------------------------------------
 import DigitalGauge from "t-digital-gauge2";
应写为
import { DigitalGauge } from 't-digital-gauge2'

使用结构赋值或者单独点语法

**Comment by xiaomitangtang** [comment]
不好意思，刚刚没注意你的问题，不是不能展示，而是value未展示的问题
已经发布新版本进行修复
![image](https://user-images.githubusercontent.com/27951909/91179153-b62f3580-e718-11ea-90db-0eac43a8445f.png)

前面的bug是由于，setOption在dom初始化之前，所以未触发相关的钩子。已经修复
另一个，是缺少了一个const   
感谢指正，已经行修复

**Comment by xiaomitangtang** [comment]
index  是三个组件共同打包的，另外三个组件单独打包到dist中，可以单独引入
后续更新也会按照这个文件目录进行更新，
如果您在使用，非常荣幸接受您的建议和意见
同时感谢您的使用和测试
